<?php

namespace ContainerZxLh4ki;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFamilleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KlOeCAw.App\Entity\Famille' shared service.
     *
     * @return \App\Entity\Famille
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KlOeCAw": it references class "App\\Entity\\Famille" but no such service exists.');
    }
}
