<?php

namespace ContainerAVmHVE8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WMae6ewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WMae6ew' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WMae6ew'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AnimalController::afficherAnimal' => ['privates', '.service_locator.YyIZgAU', 'get_ServiceLocator_YyIZgAUService', true],
            'App\\Controller\\AnimalController::index' => ['privates', '.service_locator.YyIZgAU', 'get_ServiceLocator_YyIZgAUService', true],
            'App\\Controller\\FamilleController::afficherFamille' => ['privates', '.service_locator.KlOeCAw', 'get_ServiceLocator_KlOeCAwService', true],
            'App\\Controller\\FamilleController::index' => ['privates', '.service_locator.bv3.9ld', 'get_ServiceLocator_Bv3_9ldService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AnimalController:afficherAnimal' => ['privates', '.service_locator.YyIZgAU', 'get_ServiceLocator_YyIZgAUService', true],
            'App\\Controller\\AnimalController:index' => ['privates', '.service_locator.YyIZgAU', 'get_ServiceLocator_YyIZgAUService', true],
            'App\\Controller\\FamilleController:afficherFamille' => ['privates', '.service_locator.KlOeCAw', 'get_ServiceLocator_KlOeCAwService', true],
            'App\\Controller\\FamilleController:index' => ['privates', '.service_locator.bv3.9ld', 'get_ServiceLocator_Bv3_9ldService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AnimalController::afficherAnimal' => '?',
            'App\\Controller\\AnimalController::index' => '?',
            'App\\Controller\\FamilleController::afficherFamille' => '?',
            'App\\Controller\\FamilleController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AnimalController:afficherAnimal' => '?',
            'App\\Controller\\AnimalController:index' => '?',
            'App\\Controller\\FamilleController:afficherFamille' => '?',
            'App\\Controller\\FamilleController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
