<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS2bJloR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS2bJloR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS2bJloR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS2bJloR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS2bJloR\App_KernelDevDebugContainer([
    'container.build_hash' => 'S2bJloR',
    'container.build_id' => '357fedfd',
    'container.build_time' => 1607470772,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS2bJloR');
