<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSSfwQM5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSSfwQM5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSSfwQM5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSSfwQM5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSSfwQM5\App_KernelDevDebugContainer([
    'container.build_hash' => 'SSfwQM5',
    'container.build_id' => '51934f2a',
    'container.build_time' => 1607438356,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSSfwQM5');
