<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZxLh4ki\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZxLh4ki/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZxLh4ki.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZxLh4ki\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZxLh4ki\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZxLh4ki',
    'container.build_id' => '62ced474',
    'container.build_time' => 1607562323,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZxLh4ki');
